In [1]:
import numpy as np
import pandas as pd

In [14]:
def intInput(text):
    while True:
        try:
            x = int(input(text))
            break
        except ValueError:
            print('Masukkan bilangan integer.\n')
            continue
    return x


---
# Soal 1

In [31]:
startArr = intInput('Masukkan nilai Start: ')
stopArr = intInput('Masukkan nilai Stop: ')

print(f'Nilai Start = {startArr}')
print(f'Nilai Stop {stopArr}')

Nilai Start = 1
Nilai Stop 28


#### Array 1D

In [35]:
arr = np.arange(startArr, stopArr)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

### Array 2D

In [36]:
arr.reshape(3,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

### Array 3D

In [37]:
arr.reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

___
# Soal 2